#! /bin/bash
IA_APP_ENV=$IA_APP_ENV \
NEO4J_SPOKE_USER=$NEO4J_SPOKE_USER \
NEO4J_SPOKE_PASSWORD=$NEO4J_SPOKE_PASSWORD \
NEO4J_SPOKE_URI=$NEO4J_SPOKE_URI \
PSEV_API_KEY=$PSEV_API_KEY \
PSEV_SERVICE_URL=$PSEV_SERVICE_URL \
docker-compose up web
