#! /bin/bash
APP_ENV_IA=$APP_ENV_IA \
AWS_REGION=$AWS_REGION \
NEO4J_SPOKE_HOSTNAME=$NEO4J_SPOKE_HOSTNAME \
NEO4J_SPOKE_PASS=$NEO4J_SPOKE_PASS \
NEO4J_SECRETS_NAME=$NEO4J_SECRETS_NAME \
NEO4J_SPOKE_USER=$NEO4J_SPOKE_USER \
PSEV_API_KEY=$PSEV_API_KEY \
PSEV_SECRETS_NAME=$PSEV_SECRETS_NAME \
PSEV_SERVICE_HOSTNAME=$PSEV_SERVICE_HOSTNAME \
docker compose up web
