BIOLINK_SPOKE_NODE_MAPPINGS = {
    # commented lines exist in SPOKE, but don't have exact equivalents in Biolink
    "biolink:Gene": ("Gene", "split"),
    #:"SideEffect",
    "biolink:BiologicalProcess": ("BiologicalProcess", "no-split"),
    "biolink:MolecularActivity": ("MolecularFunction", "no-split"),
    "biolink:ChemicalSubstance": ("Compound", "no-split"),
    "biolink:CellularComponent": ("CellularComponent", "no-split"),
    #:"PharmacologicClass",
    "biolink:Pathway": ("Pathway", "no-split"),
    "biolink:Disease": ("Disease", "no-split"),
    # "":"Symptom",
    "biolink:GrossAnatomicalStructure": ("Anatomy", "no-split"),
    "biolink:Protein": ("Protein", "split"),
    # "": "Food"
    "0": (False, "no-split"),  # for "any node type"
}

SPOKE_BIOLINK_NODE_MAPPINGS = {
    "Gene": "biolink:Gene",
    "SideEffect": "biolink:NamedThing",
    "BiologicalProcess": "biolink:BiologicalProcess",
    "MolecularFunction": "biolink:MolecularActivity",
    "Compound": "biolink:ChemicalSubstance",
    "CellularComponent": "biolink:CellularComponent",
    "PharmacologicClass": "biolink:NamedThing",
    "Pathway": "biolink:Pathway",
    "Disease": "biolink:Disease",
    "Symptom": "biolink:PhenotypicFeature",
    "Anatomy": "biolink:GrossAnatomicalStructure",
    "Protein": "biolink:Protein",
    "Food": "biolink:NamedThing",
}

# BIOLINK_SPOKE_EDGE_MAPPINGS = {
# not worth it right now
#     : "EXPRESSES_AeG",
#     : "PARTICIPATES_GpMF",
#     : "INTERACTS_GiG",
#     : "DOWNREGULATES_AdG",
#     : "PARTICIPATES_GpBP",
#     : "UPREGULATES_AuG",
#     : "COVARIES_GcG",
#     : "PARTICIPATES_GpPW",
#     : "PARTICIPATES_GpCC",
#     : "UPREGULATES_DuG",
#     : "ASSOCIATES_DaG",
#     : "TRANSLATEDFROM_PtG",
#     : "CAUSES_CcSE",
#     : "BINDS_CbP",
#     : "CONTRAINDICATES_CcD",
#     : "INCLUDES_PCiC",
#     : "RESEMBLES_CrC",
#     : "DOWNREGULATES_CdG",
#     : "UPREGULATES_CuG",
#     : "REGULATES_GrG",
#     : "DOWNREGULATES_DdG",
#     : "TREATS_CtD",
#     : "AFFECTS_CamG",
#     : "PALLIATES_CpD",
#     : "LOCALIZES_DlA",
#     : "PRESENTS_DpS",
#     : "RESEMBLES_DrD",
#     : "ISA_DiD",
#     : "CONTAINS_DcD",
#     : "INTERACTS_CiP",
#     : "ISA_AiA",
#     : "CONTAINS_AcA",
#     : "PARTOF_ApA",
#     : "CONTAINS_FcCM",
#     : "INTERACTS_PiP"
# }
