from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from improving_agent.models.base_model import Model
from improving_agent.models.meta_attribute import MetaAttribute
from improving_agent import util


class MetaNode(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id_prefixes=None, attributes=None):  # noqa: E501
        """MetaNode - a model defined in OpenAPI

        :param id_prefixes: The id_prefixes of this MetaNode.  # noqa: E501
        :type id_prefixes: List[str]
        :param attributes: The attributes of this MetaNode.  # noqa: E501
        :type attributes: List[MetaAttribute]
        """
        self.openapi_types = {
            'id_prefixes': List[str],
            'attributes': List[MetaAttribute]
        }

        self.attribute_map = {
            'id_prefixes': 'id_prefixes',
            'attributes': 'attributes'
        }

        self._id_prefixes = id_prefixes
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'MetaNode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MetaNode of this MetaNode.  # noqa: E501
        :rtype: MetaNode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_prefixes(self) -> List[str]:
        """Gets the id_prefixes of this MetaNode.

        List of CURIE prefixes for the node category that this TRAPI web service understands and accepts on the input.  # noqa: E501

        :return: The id_prefixes of this MetaNode.
        :rtype: List[str]
        """
        return self._id_prefixes

    @id_prefixes.setter
    def id_prefixes(self, id_prefixes: List[str]):
        """Sets the id_prefixes of this MetaNode.

        List of CURIE prefixes for the node category that this TRAPI web service understands and accepts on the input.  # noqa: E501

        :param id_prefixes: The id_prefixes of this MetaNode.
        :type id_prefixes: List[str]
        """
        if id_prefixes is None:
            raise ValueError("Invalid value for `id_prefixes`, must not be `None`")  # noqa: E501
        if id_prefixes is not None and len(id_prefixes) < 1:
            raise ValueError("Invalid value for `id_prefixes`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._id_prefixes = id_prefixes

    @property
    def attributes(self) -> List[MetaAttribute]:
        """Gets the attributes of this MetaNode.

        Node attributes provided by this TRAPI web service.  # noqa: E501

        :return: The attributes of this MetaNode.
        :rtype: List[MetaAttribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[MetaAttribute]):
        """Sets the attributes of this MetaNode.

        Node attributes provided by this TRAPI web service.  # noqa: E501

        :param attributes: The attributes of this MetaNode.
        :type attributes: List[MetaAttribute]
        """

        self._attributes = attributes
