from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from improving_agent.models.base_model import Model
from improving_agent.models.attribute import Attribute
from improving_agent import util

class NodeBinding(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, query_id=None, attributes=None):  # noqa: E501
        """NodeBinding - a model defined in OpenAPI

        :param id: The id of this NodeBinding.  # noqa: E501
        :type id: str
        :param query_id: The query_id of this NodeBinding.  # noqa: E501
        :type query_id: str
        :param attributes: The attributes of this NodeBinding.  # noqa: E501
        :type attributes: List[Attribute]
        """
        self.openapi_types = {
            'id': str,
            'query_id': str,
            'attributes': List[Attribute]
        }

        self.attribute_map = {
            'id': 'id',
            'query_id': 'query_id',
            'attributes': 'attributes'
        }

        self._id = id
        self._query_id = query_id
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'NodeBinding':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NodeBinding of this NodeBinding.  # noqa: E501
        :rtype: NodeBinding
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this NodeBinding.


        :return: The id of this NodeBinding.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this NodeBinding.


        :param id: The id of this NodeBinding.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def query_id(self) -> str:
        """Gets the query_id of this NodeBinding.


        :return: The query_id of this NodeBinding.
        :rtype: str
        """
        return self._query_id

    @query_id.setter
    def query_id(self, query_id: str):
        """Sets the query_id of this NodeBinding.


        :param query_id: The query_id of this NodeBinding.
        :type query_id: str
        """

        self._query_id = query_id

    @property
    def attributes(self) -> List[Attribute]:
        """Gets the attributes of this NodeBinding.

        A list of attributes providing further information about the node binding. This is not intended for capturing node attributes and should only be used for properties that vary from result to result.  # noqa: E501

        :return: The attributes of this NodeBinding.
        :rtype: List[Attribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[Attribute]):
        """Sets the attributes of this NodeBinding.

        A list of attributes providing further information about the node binding. This is not intended for capturing node attributes and should only be used for properties that vary from result to result.  # noqa: E501

        :param attributes: The attributes of this NodeBinding.
        :type attributes: List[Attribute]
        """
        if attributes is None:
            raise ValueError("Invalid value for `attributes`, must not be `None`")  # noqa: E501
        if attributes is not None and len(attributes) < 0:
            raise ValueError("Invalid value for `attributes`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._attributes = attributes
