from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from improving_agent.models.allow_list import AllowList
from improving_agent.models.deny_list import DenyList
from improving_agent.models.base_model import Model
from improving_agent import util

class RunnerParameters(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, allowlist=None, denylist=None):  # noqa: E501
        """RunnerParameters - a model defined in OpenAPI

        :param allowlist: The allowlist of this RunnerParameters.  # noqa: E501
        :type allowlist: AllowList
        :param denylist: The denylist of this RunnerParameters.  # noqa: E501
        :type denylist: DenyList
        """
        self.openapi_types = {
            'allowlist': AllowList,
            'denylist': DenyList
        }

        self.attribute_map = {
            'allowlist': 'allowlist',
            'denylist': 'denylist'
        }

        self._allowlist = allowlist
        self._denylist = denylist

    @classmethod
    def from_dict(cls, dikt) -> 'RunnerParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunnerParameters of this RunnerParameters.  # noqa: E501
        :rtype: RunnerParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def allowlist(self) -> AllowList:
        """Gets the allowlist of this RunnerParameters.

        List of operation providers (by infores ID) that may be used to complete operation. No others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the workflow runner.  # noqa: E501

        :return: The allowlist of this RunnerParameters.
        :rtype: AllowList
        """
        return self._allowlist

    @allowlist.setter
    def allowlist(self, allowlist: AllowList):
        """Sets the allowlist of this RunnerParameters.

        List of operation providers (by infores ID) that may be used to complete operation. No others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the workflow runner.  # noqa: E501

        :param allowlist: The allowlist of this RunnerParameters.
        :type allowlist: AllowList
        """

        self._allowlist = allowlist

    @property
    def denylist(self) -> DenyList:
        """Gets the denylist of this RunnerParameters.

        List of operation providers (by infores ID) that may not be used to complete operation. All others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the worflow runner.  # noqa: E501

        :return: The denylist of this RunnerParameters.
        :rtype: DenyList
        """
        return self._denylist

    @denylist.setter
    def denylist(self, denylist: DenyList):
        """Sets the denylist of this RunnerParameters.

        List of operation providers (by infores ID) that may not be used to complete operation. All others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the worflow runner.  # noqa: E501

        :param denylist: The denylist of this RunnerParameters.
        :type denylist: DenyList
        """

        self._denylist = denylist
